name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        working-directory: ./packages/react-chat
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        working-directory: ./packages/react-chat
        run: |
          yarn install
          yarn build:docs
      - name: Deploy
        working-directory: ./packages/react-chat
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: docs
          folder: docs
          clean: true
